### ISSUE TITLE
Whitelist not work now

### ISSUE THREAD

**Issue by k79e** [k08045kk/RejectServiceWorker#11]
Whether click the icon to add it to whitelist or manually fill the whitelist. It's just not work.

**Comment by k08045kk** [comment]
I have briefly checked it in the latest environment and it appears to be working in my environment.
I am sorry, but could you please tell me how to reproduce the problem?
[Example]
+ Browser UA (browser type and version information)
  + Example: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`
+ Extension Version.
  +  Example: `0.4.0`
+ URL of the target site.
  + Example: `https://backlog.com/ja/git-tutorial/`
+ What did you see that made you think the whitelist was not working?
  + Example: not shown in `chrome://serviceworker-internals` (it did in my environment)

**Comment by k79e** [comment]
Unregister all sw first.
Then using your extension on app store.

Enter mail.google.com in the whitelist.
Open the google email.

I don't see any sw in chrome://serviceworker-internals/
It always blank!!!

**Comment by k79e** [comment]
Hi I found that the whitelist is not work only for mail.google.com !!!

**Comment by k08045kk** [comment]
I confirmed the reproduction of the problem phenomenon. Whitelisting Gmail (mail.google.com) doesn't add Gmail service workers.

The details of the cause are still unknown, but using the user script version seems to be the most practical workaround.
https://www.bugbugnow.net/2020/03/Reject-to-register-a-ServiceWorker.html

**Comment by k08045kk** [comment]
It seems that the service worker for mail.google.com needs to add not only “mail.google.com” but also “chat.google.com” to the additional white list.

The detailed behavior of mail.google.com is unknown, but it appears that this is occurring because the service worker for chat.google.com is not attempting to register the service worker for mail.google.com if the service worker for chat.google.com is unable to register successfully.

Related: サブフレームの Service Worker をどう扱うか #23
